### ISSUE TITLE
Only output types and methods from the original header

### ISSUE THREAD

**Issue by jonas** [kornilova-l/scala-native-bindgen#13]
In the `native types` test both the `uchar.h` and `stddef.h` header files are included which depending on the platform will generate additional type aliases and structs definitions for types read from those headers even if those types are unused.

**Comment by jonas** [comment]
Depends on the IR work done in #6

**Comment by kornilova-l** [comment]
@jonas, should we remove unused types and structs that are declared only in included headers or all unused types and structs?

**Comment by jonas** [comment]
Depends on type representation in the IR: #52

**Comment by kornilova-l** [comment]
How do we decide that type may be removed?
We already have filtering by prefix by prefix that should remove platform specific types.
We should not remove all unused typedefs simply because they may be used by other bindings.

**Comment by jonas** [comment]
This issue can probably be closed in favour of #2. We need to track which header file declared a type and based on that we can prune (or ignore) any type not declared in the header file for which we are generating bindings.

Note that eventually we need to support generating bindings for multiple header files.

**Comment by jonas** [comment]
I've retitled the issue based on the above comment.

**Comment by jonas** [comment]
From looking into this, it should be possible to use `clang::ASTContext.getSourceManager()` to get the file name of any `clang::Decl` processed by `TreeVisitor`.

Methods not in the original header can be discarded right away, while types will have to be added to the IR in case we have to reference it, e.g. `stdio.FILE`, or resolve it, e.g. `type a = __darwin_a; type __darwin_a = native.CInt` => `type a = native.CInt`.

On macOS I noticed that some standard headers are merely wrappers, e.g. `/usr/include/ctype.h` leaves all declarations to `/usr/include/_ctype.h`. So a lightweight way to configure and support such a use case is necessary.

**Comment by jonas** [comment]
I'm also wondering if we should put in place a proper class to track the origin of a declaration. `Main` can then add the initial instance to the IR and load+add known instances from `stdHeader.config`.

The class should contain:
 - Include path or basename (ideally paths and basenames)
 - Scala package+object name
