### ISSUE TITLE
Check if codegen outputs correct bindings for packed structs

### ISSUE THREAD

**Issue by kornilova-l** [kornilova-l/scala-native-bindgen#21]

**Comment by jonas** [comment]
Depending on whether clang exposes it in the AST that a struct was annotated wit `__attribute__((__packed__))`, the resolution of this ticket might be to simply document it as a limitation.

**Comment by kornilova-l** [comment]
Packed structs are currently not supported in Scala Native scala-native/scala-native#37

**Comment by kornilova-l** [comment]
I will add warning for such structs
