### ISSUE TITLE
Add option to provide the package name of the generated code

### ISSUE THREAD

**Issue by jonas** [kornilova-l/scala-native-bindgen#27]
A sensible default could either be hard-coded or based on the path of the file.

**Comment by kornilova-l** [comment]
I don't think default value is needed.
If we decide to use path of the file then how do we decide what part of path is the package? It is not guaranteed to be in `src/main/scala` dir

**Comment by kornilova-l** [comment]
I added command line option for package name without default value #43

**Comment by jonas** [comment]
OK, makes sense to make it optional.
