### ISSUE TITLE
Update NEWS.md and documentation for 0.1

### ISSUE THREAD

**Issue by jonas** [kornilova-l/scala-native-bindgen#53]
- Add newest completed improvements to the NEWS.md file
- Use the current [Design doc](https://github.com/kornilova-l/scala-native-bindgen/wiki/Design-doc) as a base for a user guide (current limitations) and documentation related to the project goals and roadmap.

**Comment by kornilova-l** [comment]
Updated [NEWS.md](https://github.com/kornilova-l/scala-native-bindgen/blob/master/NEWS.md)

**Comment by kornilova-l** [comment]
@jonas, I added _current limitations_ section to  [README.md](https://github.com/kornilova-l/scala-native-bindgen/blob/master/README.md). Is it okay? Should I create a release now (with the links to docker images)?

**Comment by jonas** [comment]
Yes please. I can push a container sometime this weekend

**Comment by kornilova-l** [comment]
I wrote [draft of the release](https://github.com/kornilova-l/scala-native-bindgen/releases)
_Release Highlights_ section contains only the news that might be interesting for end user.
Maybe you can publish the release after pushing a container.

**Comment by jonas** [comment]
Yes,  that's great.

**Comment by jonas** [comment]
Please create the tag for 0.1 and publish.
