### ISSUE TITLE
Reorganize repo into subprojects

### ISSUE THREAD

**Issue by jonas** [kornilova-l/scala-native-bindgen#7]
In preparation for including bindings we should probably reorganize the repository soon.

One option would be:

- bindgen: the current C++ code and cmake project
- tests: the test suite, basically what is currently there, with tooling to run using CI
- bindings: sbt project(s) with library bindings to publish to Maven Central, e.g.
  - uv
  - nurses
  - readline

Based on stability and progress, it might also make sense to have a tooling and sbt-plugin to make it possible to integrate the binding generator into existing projects.

**Comment by kornilova-l** [comment]
@jonas, I moved the bindgen project to `bindgen` directory, so it is separated from tests #45 
Will this be enough to close the issue? 
Generating and publishing bindings is a different story
