### ISSUE TITLE
RFC: Ask GitHub to detach this fork from 

### ISSUE THREAD

**Issue by jonas** [kornilova-l/scala-native-bindgen#71]
Given that we have invested in setting up this project, for example created issues, I propose that we ask GitHub support to turn it into a standalone repository. This would make a lot of things easier such as creating PRs, which sometimes accidentally end up in mrRosset/scala-native-bindgen.

https://help.github.com/articles/why-are-my-contributions-not-showing-up-on-my-profile/#commit-was-made-in-a-fork

> To detach the fork and turn it into a standalone repository on GitHub, contact GitHub Support. If the fork has forks of its own, let support know if the forks should move with your repository into a new network or remain in the current network. For more information, see "About forks."

**Comment by kornilova-l** [comment]
I've sent request to support

**Comment by jonas** [comment]
Yay, they've made the change.
