### ISSUE TITLE
Generate type for inner anonymous structs

### ISSUE THREAD

**Issue by kornilova-l** [kornilova-l/scala-native-bindgen#77]
This code:
```c
struct myStruct {
    struct {
        int a;
    } innerStruct;
};
```
Generates following type:
```scala
type struct_myStruct = native.CStruct1[native.CArray[Byte, native.Nat.Digit[native.Nat._3, native.Nat._2]]]
```
So inner anonymous struct is represented as an array of bytes.
It should be possible to generate type for the inner struct:
```scala
type struct_myStruct_anonymous0 = native.CStruct1[native.CInt]
type struct_myStruct = native.CStruct1[struct_myStruct_anonymous0]
```

**Comment by ekrich** [comment]
I was thinking for pass by value that perhaps you could generate a pointer and then just leave a comment if you can in your generated code that a helper function is needed. The complex lib is all pass by value but is implemented with pointers and helper functions.

**Comment by kornilova-l** [comment]
Also functions may have return value or parameters of anonymous struct type:
```c
void foo(struct { int a; } * s) {
    // ...
}

struct {
    int result;
} * bar() {
    // ...
}
```
Not sure if it is ever used but such library compiles and functions can be called from Scala Native code
