### ISSUE TITLE
Fix case when typedef references struct that is not yet declared

### ISSUE THREAD

**Issue by kornilova-l** [kornilova-l/scala-native-bindgen#88]
Generating bindings for `/usr/include/uv.h` gives lots of errors and does not output Scala code:
```
Failed to get declaration for struct __fsid_t
Failed to get declaration for struct _IO_FILE
Failed to get declaration for struct __va_list_tag
...
```
The problem is that typedef for struct can be located above struct declaration:
```c
typedef struct myStruct mystruct;

struct myStruct {
    int a;
};
```
So when `TreeVisitor` visits typedef it is unable to translate `struct myStruct` because type is not yet in `TypeTranslator::aliasesMap`

**Comment by jonas** [comment]
This is similar to #78 or at least it looks like both would require the same sort of lazy behavior.

**Comment by kornilova-l** [comment]
Yes, it is similar
